import type { AgentStatus, JournalEvent } from "../agent";

interface ExportViewProps {
  status: AgentStatus | null;
  journal: JournalEvent[];
  exportNote: string | null;
  onExportExcel: () => void;
  terminal?: boolean;
}

export default function ExportView({
  status,
  journal,
  exportNote,
  onExportExcel,
}: ExportViewProps) {
  const exportCreated = journal.find((e) => e.event_type === "EXPORT_CREATED");
  const exportFailed = journal.find((e) => e.event_type === "EXPORT_FAILED");

  return (
    <div className="export-view-container" aria-label="Export View">
      <div className="export-header">
        <div className="export-title-group">
          <h2>Export & Analytical Artifacts</h2>
          <span className="subtitle-text">
            Generate and export decision-support workbooks and broadcast intelligence reports
          </span>
        </div>
      </div>

      <div className="export-cards-grid">
        {/* Excel Workbook Export Card */}
        <div className="export-card">
          <div className="card-badge-row">
            <span className="format-badge badge-excel">EXCEL (.XLSX)</span>
            <span className="type-badge">Primary Decision Workbook</span>
          </div>

          <h3 className="card-heading">NAS FM Multi-Sheet Programming Workbook</h3>
          <p className="card-desc">
            Complete multi-tab analytical spreadsheet containing Session Summary, Broadcast Timeline, Content Blocks, Clock Wheels, Daypart Breakdown, and Recurrent Elements.
          </p>

          <div className="card-action-box">
            <button
              type="button"
              className="btn btn-primary btn-large"
              onClick={onExportExcel}
              disabled={!status?.session_id}
            >
              Export Excel Workbook
            </button>
            {!status?.session_id && (
              <span className="action-hint">Active session required to generate workbook</span>
            )}
          </div>

          {/* Export Status Feedbacks */}
          {exportNote && !exportCreated && !exportFailed && (
            <div className="export-status-banner banner-in-progress" role="status">
              <span className="status-spinner">⏳</span>
              <span>{exportNote}</span>
            </div>
          )}

          {exportCreated && (
            <div className="export-status-banner banner-success" role="status">
              <span className="status-check">✓</span>
              <div className="banner-text-group">
                <span className="banner-strong">Export complete:</span>
                <span className="banner-path font-mono">{exportCreated.message}</span>
              </div>
            </div>
          )}

          {exportFailed && (
            <div className="export-status-banner banner-error" role="alert">
              <span className="status-err">✕</span>
              <div className="banner-text-group">
                <span className="banner-strong">Export failed:</span>
                <span className="banner-path">{exportFailed.message}</span>
              </div>
            </div>
          )}
        </div>

        {/* Structured Reports Card */}
        <div className="export-card">
          <div className="card-badge-row">
            <span className="format-badge badge-markdown">JSON / MARKDOWN</span>
            <span className="type-badge">Audit & Engine Artifacts</span>
          </div>

          <h3 className="card-heading">Executive Summary & Audit Reports</h3>
          <p className="card-desc">
            Automated session artifacts generated by the background monitoring worker at session completion.
          </p>

          {status?.result ? (
            <div className="reports-manifest">
              <div className="manifest-item">
                <span className="manifest-label">Machine-Readable Report:</span>
                <span className="manifest-val font-mono">{status.result.report_json}</span>
              </div>
              <div className="manifest-item">
                <span className="manifest-label">Markdown Executive Summary:</span>
                <span className="manifest-val font-mono">{status.result.report_markdown}</span>
              </div>
              <div className="manifest-summary-box">
                <span className="summary-title">Executive Summary:</span>
                <p className="summary-text">{status.result.executive_summary}</p>
              </div>
            </div>
          ) : (
            <div className="manifest-empty">
              <p>Reports are finalized automatically when the session completes.</p>
              <span className="manifest-state-tag">
                Current status: {status?.state ?? "Idle"}
              </span>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
